# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 550))
        MainWindow.setMaximumSize(QtCore.QSize(800, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 52, 161, 441))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 16, 161, 111))
        self.label.setStyleSheet("image: url(:/peimaiqi/zhonglipeimaiqi.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(0, 303, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(66, 303, 51, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(126, 303, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setGeometry(QtCore.QRect(0, 334, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox)
        self.label_34.setGeometry(QtCore.QRect(68, 334, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 410, 141, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 136, 161, 164))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 2, 2, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 7, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 10, 2, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 4, 2, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 12, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout.addWidget(self.line_17, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 12, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 10, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 2, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout.addWidget(self.line_16, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 9, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 7, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 12, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 2, 0, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 4, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 9, 1, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout.addWidget(self.line_18, 13, 0, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout.addWidget(self.line_19, 13, 2, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.groupBox)
        self.line_14.setGeometry(QtCore.QRect(0, 320, 161, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.groupBox)
        self.line_15.setGeometry(QtCore.QRect(0, 350, 161, 20))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_58 = QtWidgets.QFrame(self.groupBox)
        self.line_58.setGeometry(QtCore.QRect(0, 390, 161, 20))
        self.line_58.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_58.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_58.setObjectName("line_58")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(40, 370, 91, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(170, 10, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_43.setObjectName("label_43")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 50, 161, 441))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(0, 16, 161, 111))
        self.label_13.setStyleSheet("image: url(:/peimaiqi/zhonglipeimaiqi.png);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(0, 303, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(66, 303, 51, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(126, 303, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(0, 334, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(68, 334, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 410, 141, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 136, 161, 164))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 2, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_2.addWidget(self.line_20, 6, 1, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_2.addWidget(self.line_21, 2, 2, 1, 1)
        self.line_22 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout_2.addWidget(self.line_22, 7, 0, 1, 1)
        self.line_23 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout_2.addWidget(self.line_23, 10, 2, 1, 1)
        self.line_24 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.gridLayout_2.addWidget(self.line_24, 4, 2, 1, 1)
        self.line_25 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.gridLayout_2.addWidget(self.line_25, 12, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 0, 1, 1)
        self.line_26 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.gridLayout_2.addWidget(self.line_26, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 2, 1, 1)
        self.line_27 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.gridLayout_2.addWidget(self.line_27, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 9, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 12, 0, 1, 1)
        self.line_28 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.gridLayout_2.addWidget(self.line_28, 10, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 6, 2, 1, 1)
        self.line_29 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.gridLayout_2.addWidget(self.line_29, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 9, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 6, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 3, 0, 1, 1)
        self.line_30 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.gridLayout_2.addWidget(self.line_30, 7, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 12, 2, 1, 1)
        self.line_31 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.gridLayout_2.addWidget(self.line_31, 3, 1, 1, 1)
        self.line_32 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.gridLayout_2.addWidget(self.line_32, 2, 0, 1, 1)
        self.line_33 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.gridLayout_2.addWidget(self.line_33, 4, 0, 1, 1)
        self.line_34 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_34.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.gridLayout_2.addWidget(self.line_34, 9, 1, 1, 1)
        self.line_35 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.gridLayout_2.addWidget(self.line_35, 13, 0, 1, 1)
        self.line_36 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_36.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.gridLayout_2.addWidget(self.line_36, 13, 2, 1, 1)
        self.line_37 = QtWidgets.QFrame(self.groupBox_2)
        self.line_37.setGeometry(QtCore.QRect(0, 320, 161, 20))
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.line_38 = QtWidgets.QFrame(self.groupBox_2)
        self.line_38.setGeometry(QtCore.QRect(0, 350, 161, 20))
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.line_59 = QtWidgets.QFrame(self.groupBox_2)
        self.line_59.setGeometry(QtCore.QRect(0, 390, 161, 20))
        self.line_59.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_59.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_59.setObjectName("line_59")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_11.setGeometry(QtCore.QRect(40, 370, 91, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(590, 50, 161, 441))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(0, 16, 161, 111))
        self.label_25.setStyleSheet("image: url(:/peimaiqi/zhonglipeimaiqi.png);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(0, 303, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(66, 303, 51, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(126, 303, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_37 = QtWidgets.QLabel(self.groupBox_3)
        self.label_37.setGeometry(QtCore.QRect(0, 334, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_3)
        self.label_38.setGeometry(QtCore.QRect(68, 334, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 410, 141, 25))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 136, 161, 164))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 1, 2, 1, 1)
        self.line_39 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_39.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.gridLayout_3.addWidget(self.line_39, 6, 1, 1, 1)
        self.line_40 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_40.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.gridLayout_3.addWidget(self.line_40, 2, 2, 1, 1)
        self.line_41 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_41.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.gridLayout_3.addWidget(self.line_41, 7, 0, 1, 1)
        self.line_42 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_42.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.gridLayout_3.addWidget(self.line_42, 10, 2, 1, 1)
        self.line_43 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.gridLayout_3.addWidget(self.line_43, 4, 2, 1, 1)
        self.line_44 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_44.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.gridLayout_3.addWidget(self.line_44, 12, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.line_45 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_45.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.gridLayout_3.addWidget(self.line_45, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 3, 2, 1, 1)
        self.line_46 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_46.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.gridLayout_3.addWidget(self.line_46, 0, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 9, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 12, 0, 1, 1)
        self.line_47 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_47.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.gridLayout_3.addWidget(self.line_47, 10, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 6, 2, 1, 1)
        self.line_48 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_48.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.gridLayout_3.addWidget(self.line_48, 0, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 9, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_3.addWidget(self.label_40, 6, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 3, 0, 1, 1)
        self.line_49 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_49.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.gridLayout_3.addWidget(self.line_49, 7, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.gridLayout_3.addWidget(self.label_42, 12, 2, 1, 1)
        self.line_50 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_50.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.gridLayout_3.addWidget(self.line_50, 3, 1, 1, 1)
        self.line_51 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_51.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.gridLayout_3.addWidget(self.line_51, 2, 0, 1, 1)
        self.line_52 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_52.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_52.setObjectName("line_52")
        self.gridLayout_3.addWidget(self.line_52, 4, 0, 1, 1)
        self.line_53 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_53.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_53.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_53.setObjectName("line_53")
        self.gridLayout_3.addWidget(self.line_53, 9, 1, 1, 1)
        self.line_54 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_54.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_54.setObjectName("line_54")
        self.gridLayout_3.addWidget(self.line_54, 13, 0, 1, 1)
        self.line_55 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_55.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_55.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_55.setObjectName("line_55")
        self.gridLayout_3.addWidget(self.line_55, 13, 2, 1, 1)
        self.line_56 = QtWidgets.QFrame(self.groupBox_3)
        self.line_56.setGeometry(QtCore.QRect(0, 320, 161, 20))
        self.line_56.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_56.setObjectName("line_56")
        self.line_57 = QtWidgets.QFrame(self.groupBox_3)
        self.line_57.setGeometry(QtCore.QRect(0, 350, 161, 20))
        self.line_57.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_57.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_57.setObjectName("line_57")
        self.line_60 = QtWidgets.QFrame(self.groupBox_3)
        self.line_60.setGeometry(QtCore.QRect(0, 390, 161, 20))
        self.line_60.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_60.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_60.setObjectName("line_60")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_12.setGeometry(QtCore.QRect(40, 370, 91, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action1_2 = QtWidgets.QAction(MainWindow)
        self.action1_2.setObjectName("action1_2")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_15 = QtWidgets.QAction(MainWindow)
        self.action_15.setObjectName("action_15")
        self.menu.addAction(self.action_15)
        self.menu.addSeparator()
        self.menu.addAction(self.action_5)
        self.menu_3.addAction(self.action_7)
        self.menu_3.addAction(self.action_8)
        self.menu_3.addAction(self.action_9)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.qidong1)
        self.pushButton_3.clicked.connect(MainWindow.tingzhi1)
        self.pushButton_5.clicked.connect(MainWindow.qidong2)
        self.pushButton_8.clicked.connect(MainWindow.qidong3)
        self.pushButton_6.clicked.connect(MainWindow.tingzhi2)
        self.pushButton_9.clicked.connect(MainWindow.tingzhi3)
        self.pushButton.clicked.connect(MainWindow.shezhi1)
        self.pushButton_4.clicked.connect(MainWindow.shezhi2)
        self.pushButton_7.clicked.connect(MainWindow.shezhi3)
        self.action_13.triggered.connect(MainWindow.banzushezhi)
        self.action_15.triggered.connect(MainWindow.bangzhu)
        self.action_5.triggered.connect(MainWindow.guanyu)
        self.action_7.triggered.connect(MainWindow.ribaobiao)
        self.action_8.triggered.connect(MainWindow.banzubaobiao)
        self.action_9.triggered.connect(MainWindow.yuebaobiao)
        self.action_4.triggered.connect(MainWindow.close)
        self.pushButton_10.clicked.connect(MainWindow.qingbaojing1)
        self.pushButton_11.clicked.connect(MainWindow.qingbaojing2)
        self.pushButton_12.clicked.connect(MainWindow.qingbaojing3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "配麦器01"))
        self.label_10.setText(_translate("MainWindow", " 目标流量"))
        self.pushButton.setText(_translate("MainWindow", "设置"))
        self.label_33.setText(_translate("MainWindow", " 当前状态"))
        self.pushButton_2.setText(_translate("MainWindow", "启动"))
        self.pushButton_3.setText(_translate("MainWindow", "停止"))
        self.label_12.setText(_translate("MainWindow", " 目标流量："))
        self.label_8.setText(_translate("MainWindow", " 今日流量："))
        self.label_6.setText(_translate("MainWindow", " 当班流量："))
        self.label_4.setText(_translate("MainWindow", " 瞬时流量："))
        self.label_2.setText(_translate("MainWindow", " 累计流量："))
        self.pushButton_10.setText(_translate("MainWindow", "清除报警"))
        self.label_43.setText(_translate("MainWindow", "发达面粉集团重力式配麦器管理系统"))
        self.groupBox_2.setTitle(_translate("MainWindow", "配麦器02"))
        self.label_14.setText(_translate("MainWindow", " 目标流量"))
        self.pushButton_4.setText(_translate("MainWindow", "设置"))
        self.label_35.setText(_translate("MainWindow", " 当前状态"))
        self.pushButton_5.setText(_translate("MainWindow", "启动"))
        self.pushButton_6.setText(_translate("MainWindow", "停止"))
        self.label_16.setText(_translate("MainWindow", " 目标流量："))
        self.label_19.setText(_translate("MainWindow", " 今日流量："))
        self.label_21.setText(_translate("MainWindow", " 当班流量："))
        self.label_22.setText(_translate("MainWindow", " 瞬时流量："))
        self.label_23.setText(_translate("MainWindow", " 累计流量："))
        self.pushButton_11.setText(_translate("MainWindow", "清除报警"))
        self.groupBox_3.setTitle(_translate("MainWindow", "配麦器03"))
        self.label_26.setText(_translate("MainWindow", " 目标流量"))
        self.pushButton_7.setText(_translate("MainWindow", "设置"))
        self.label_37.setText(_translate("MainWindow", " 当前状态"))
        self.pushButton_8.setText(_translate("MainWindow", "启动"))
        self.pushButton_9.setText(_translate("MainWindow", "停止"))
        self.label_28.setText(_translate("MainWindow", " 目标流量："))
        self.label_31.setText(_translate("MainWindow", " 今日流量："))
        self.label_39.setText(_translate("MainWindow", " 当班流量："))
        self.label_40.setText(_translate("MainWindow", " 瞬时流量："))
        self.label_41.setText(_translate("MainWindow", " 累计流量："))
        self.pushButton_12.setText(_translate("MainWindow", "清除报警"))
        self.menu.setTitle(_translate("MainWindow", "系统"))
        self.menu_3.setTitle(_translate("MainWindow", "报表"))
        self.action_4.setText(_translate("MainWindow", "退出"))
        self.action_5.setText(_translate("MainWindow", "关于"))
        self.action_7.setText(_translate("MainWindow", "日报表"))
        self.action_8.setText(_translate("MainWindow", "班组报表"))
        self.action_9.setText(_translate("MainWindow", "月报表"))
        self.action1.setText(_translate("MainWindow", "参数设置"))
        self.action1_2.setText(_translate("MainWindow", "网络设置"))
        self.action_12.setText(_translate("MainWindow", "数据库设置"))
        self.action_13.setText(_translate("MainWindow", "班组设置"))
        self.action_15.setText(_translate("MainWindow", "帮助"))
import peimaiqi_rc
